name: uikit_bindings
description: "Bindings of UIKit components for Flutter using FFI."
version: 0.0.1-dev.0
homepage: https://github.com/orestesgaolin/uikit-bindings
repository: https://github.com/orestesgaolin/uikit-bindings
issue_tracker: https://github.com/orestesgaolin/uikit-bindings/issues

platforms:
  ios:

topics:
  - flutter
  - ios
  - uikit
  - ffi
  - bindings

environment:
  sdk: ^3.9.2
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  objective_c: ^9.0.0-dev.0

dev_dependencies:
  ffigen: ^20.0.0-dev.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  logging: ^1.3.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
